[package]
name = "codl3-zksync"
version = "0.1.0"
edition = "2021"
authors = ["CODL3 Team"]
description = "CODL3 - zkSync Hyperchains Implementation"

[[bin]]
name = "codl3-zksync"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4", features = ["derive"] }