// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title COLDL3Settlement — L3 Batch Settlement on zkSync Era
/// @notice Verifies SP1 proofs of C0DL3 block execution and commits state roots.
/// @dev Deployed on zkSync Era (L2). Settlement path:
///      L3 block → SP1 Groth16 proof → this contract → Ethereum L1 (via Era)
///
///      The sequencer batches proven blocks and submits them here. Each batch
///      contains one SP1 proof covering a range of L3 blocks. The contract
///      verifies the proof against the SP1 verifier gateway and records the
///      new state root — creating a trustless L3→L2 state bridge.
contract COLDL3Settlement {
    // ── SP1 Verifier Interface ─────────────────────────────────────────────
    //
    // SP1 deploys a verifier gateway on major chains. We call it to verify
    // Groth16/PLONK proofs generated by the C0DL3 prover service.

    /// @notice SP1 verifier gateway address on zkSync Era.
    address public immutable sp1Verifier;

    /// @notice SP1 program verification key hash.
    /// Identifies the guest program (program/src/main.rs) that generated the proof.
    /// Derived from the guest ELF via: coldl3-prover --export-vkey
    bytes32 public immutable programVKeyHash;

    // ── State ──────────────────────────────────────────────────────────────

    /// @notice Latest committed L3 state root.
    bytes32 public stateRoot;

    /// @notice Latest committed L3 block height.
    uint64 public blockHeight;

    /// @notice Latest committed shielded pool note tree root.
    bytes32 public noteTreeRoot;

    /// @notice Total batches settled.
    uint64 public batchCount;

    /// @notice Sequencer address (authorized to submit batches).
    address public sequencer;

    /// @notice Mapping of settled block heights (for duplicate prevention).
    mapping(uint64 => bool) public settledBlocks;

    // ── Events ─────────────────────────────────────────────────────────────

    event BatchSettled(
        uint64 indexed batchId,
        uint64 indexed blockHeight,
        bytes32 prevStateRoot,
        bytes32 newStateRoot,
        bytes32 noteTreeRoot,
        uint32 txCount,
        uint64 totalGasUsed
    );

    event SequencerUpdated(address indexed oldSequencer, address indexed newSequencer);

    // ── Errors ─────────────────────────────────────────────────────────────

    error UnauthorizedSequencer();
    error BlockAlreadySettled(uint64 height);
    error StateRootMismatch(bytes32 expected, bytes32 got);
    error InvalidProof();
    error InvalidPublicValues();

    // ── Constructor ────────────────────────────────────────────────────────

    /// @param _sp1Verifier SP1 verifier gateway address on zkSync Era
    /// @param _programVKeyHash Hash of the SP1 guest program verification key
    /// @param _sequencer Initial sequencer address
    /// @param _genesisStateRoot Genesis L3 state root
    constructor(
        address _sp1Verifier,
        bytes32 _programVKeyHash,
        address _sequencer,
        bytes32 _genesisStateRoot
    ) {
        sp1Verifier = _sp1Verifier;
        programVKeyHash = _programVKeyHash;
        sequencer = _sequencer;
        stateRoot = _genesisStateRoot;
    }

    // ── Settlement ─────────────────────────────────────────────────────────

    /// @notice Settle an L3 block by verifying its SP1 proof.
    ///
    /// @dev The proof's public values encode a BlockExecutionClaim (152 bytes):
    ///   [0..8)    block_height      (u64 LE)
    ///   [8..40)   prev_state_root   (32 bytes)
    ///   [40..72)  new_state_root    (32 bytes)
    ///   [72..104) tx_merkle_root    (32 bytes)
    ///   [104..108) tx_count         (u32 LE)
    ///   [108..116) total_gas_used   (u64 LE)
    ///   [116..148) note_tree_root   (32 bytes)
    ///   [148..152) nullifier_count  (u32 LE)
    ///
    /// @param publicValues BlockExecutionClaim encoded as 152 bytes
    /// @param proofBytes SP1 Groth16/PLONK proof bytes
    function settleBatch(
        bytes calldata publicValues,
        bytes calldata proofBytes
    ) external {
        if (msg.sender != sequencer) revert UnauthorizedSequencer();
        if (publicValues.length < 152) revert InvalidPublicValues();

        // Decode BlockExecutionClaim from public values
        uint64 claimBlockHeight = _readU64(publicValues, 0);
        bytes32 prevStateRoot = _readBytes32(publicValues, 8);
        bytes32 newStateRoot = _readBytes32(publicValues, 40);
        // tx_merkle_root at offset 72 — verified by SP1 proof
        uint32 txCount = _readU32(publicValues, 104);
        uint64 totalGasUsed = _readU64(publicValues, 108);
        bytes32 claimNoteTreeRoot = _readBytes32(publicValues, 116);
        // nullifier_count at offset 148 — verified by SP1 proof

        // Verify chain continuity: proof's prev_state_root must match our latest
        if (prevStateRoot != stateRoot) {
            revert StateRootMismatch(stateRoot, prevStateRoot);
        }

        // Prevent duplicate settlement
        if (settledBlocks[claimBlockHeight]) {
            revert BlockAlreadySettled(claimBlockHeight);
        }

        // Verify SP1 proof against the verifier gateway
        // Reverts if proof is invalid.
        (bool success,) = sp1Verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(bytes32,bytes,bytes)",
                programVKeyHash,
                publicValues,
                proofBytes
            )
        );
        if (!success) revert InvalidProof();

        // Commit new state
        stateRoot = newStateRoot;
        blockHeight = claimBlockHeight;
        noteTreeRoot = claimNoteTreeRoot;
        settledBlocks[claimBlockHeight] = true;
        batchCount++;

        emit BatchSettled(
            batchCount,
            claimBlockHeight,
            prevStateRoot,
            newStateRoot,
            claimNoteTreeRoot,
            txCount,
            totalGasUsed
        );
    }

    // ── Admin ──────────────────────────────────────────────────────────────

    /// @notice Update sequencer address. Only callable by current sequencer.
    function setSequencer(address _newSequencer) external {
        if (msg.sender != sequencer) revert UnauthorizedSequencer();
        emit SequencerUpdated(sequencer, _newSequencer);
        sequencer = _newSequencer;
    }

    // ── Views ──────────────────────────────────────────────────────────────

    /// @notice Check if a block has been settled.
    function isSettled(uint64 height) external view returns (bool) {
        return settledBlocks[height];
    }

    /// @notice Get the current settlement state.
    function getState() external view returns (
        bytes32 currentStateRoot,
        uint64 currentBlockHeight,
        bytes32 currentNoteTreeRoot,
        uint64 totalBatches
    ) {
        return (stateRoot, blockHeight, noteTreeRoot, batchCount);
    }

    // ── Internal Helpers ───────────────────────────────────────────────────
    //
    // Read little-endian encoded integers from calldata (matching Rust's to_le_bytes).

    function _readU64(bytes calldata data, uint256 offset) internal pure returns (uint64) {
        uint64 v;
        for (uint256 i = 0; i < 8; i++) {
            v |= uint64(uint8(data[offset + i])) << (i * 8);
        }
        return v;
    }

    function _readU32(bytes calldata data, uint256 offset) internal pure returns (uint32) {
        uint32 v;
        for (uint256 i = 0; i < 4; i++) {
            v |= uint32(uint8(data[offset + i])) << (i * 8);
        }
        return v;
    }

    function _readBytes32(bytes calldata data, uint256 offset) internal pure returns (bytes32) {
        bytes32 v;
        assembly {
            v := calldataload(add(data.offset, offset))
        }
        return v;
    }
}
