# zkC0DL3 Testnet Configuration
# Production-ready testnet configuration with all features enabled

[testnet]
name = "zkc0dl3-testnet"
version = "0.1.0"
description = "zkC0DL3 Testnet - Production STARK Implementation"
chain_id = 1337
network_id = 1337

[network]
# P2P Network Configuration
p2p_port = 30303
max_peers = 50
discovery_enabled = true
nat_traversal = true
upnp_enabled = true

# RPC Configuration
rpc_enabled = true
rpc_port = 8545
rpc_host = "127.0.0.1"
rpc_cors = ["*"]
rpc_apis = ["eth", "net", "web3", "personal", "miner", "admin"]

# WebSocket Configuration
ws_enabled = true
ws_port = 8546
ws_host = "127.0.0.1"
ws_origins = ["*"]

[mining]
# Mining Configuration
algorithm = "cn-upx2"
mode = "standard"  # standard, memory_modified, auto
target_block_time = 60
difficulty_adjustment_interval = 2016
mining_enabled = true

# Merge Mining Configuration
merge_mining_enabled = true
merge_mining_interval = 60
fuego_daemon_url = "http://127.0.0.1:18081"
fuego_wallet_address = ""

[privacy]
# STARK Proof System
stark_proofs_enabled = true
stark_security_parameter = 128
stark_field_extension = "quadratic"
stark_batching_method = "batch"

# Address Encryption
address_encryption_enabled = true
encryption_algorithm = "chacha20poly1305"
key_derivation_function = "pbkdf2"

# Transaction Privacy
transaction_privacy_enabled = true
amount_privacy_enabled = true
balance_privacy_enabled = true
timing_privacy_enabled = true

# Advanced Privacy Features
cross_chain_privacy_enabled = true
mining_privacy_enabled = true
privacy_aggregation_enabled = true
recursive_proofs_enabled = true

[security]
# Security Vulnerability Fixes
vulnerability_fixes_enabled = true
secure_rng_enabled = true
input_validation_enabled = true
timing_attack_protection_enabled = true
memory_safety_enabled = true

# Cryptographic Security
key_management_enabled = true
secure_key_storage = true
zeroization_enabled = true

[performance]
# Performance Optimization
parallel_processing_enabled = true
proof_caching_enabled = true
memory_optimization_enabled = true
cpu_optimization_enabled = true

# Caching Configuration
cache_size_mb = 512
cache_eviction_policy = "lru"
proof_cache_ttl = 3600

# Parallel Processing
max_worker_threads = 8
batch_size = 100
chunk_size = 1000

[xfg_integration]
# XFG Winterfell Integration
winterfell_starks_enabled = true
fuego_sync_enabled = true
sync_interval = 30

# Token Management
heat_token_bridging_enabled = true
cold_token_generation_enabled = true
token_verification_enabled = true

# Fuego Integration
fuego_connection_timeout = 30
fuego_retry_attempts = 3
fuego_block_confirmation_required = 6

[logging]
# Logging Configuration
level = "info"
format = "json"
output = "file"
file_path = "./logs/testnet.log"
max_file_size_mb = 100
max_files = 10

# Log Categories
log_mining = true
log_privacy = true
log_security = true
log_performance = true
log_network = true
log_xfg_integration = true

[monitoring]
# Monitoring Configuration
metrics_enabled = true
metrics_port = 9090
metrics_path = "/metrics"

# Health Checks
health_check_interval = 30
health_check_timeout = 10

# Performance Monitoring
cpu_monitoring = true
memory_monitoring = true
network_monitoring = true
disk_monitoring = true

[database]
# Database Configuration
type = "rocksdb"
path = "./data/db"
cache_size_mb = 256
max_open_files = 1000
compression = true

# Backup Configuration
backup_enabled = true
backup_interval = 3600
backup_retention_days = 7
backup_path = "./backups"

[consensus]
# Consensus Configuration
consensus_algorithm = "proof_of_work"
block_reward = 0  # No block rewards in C0DL3
transaction_fees_enabled = true
gas_limit = 30000000
gas_price = 1000000000  # 1 fwei

[development]
# Development Configuration
dev_mode = true
fast_sync = true
skip_verification = false
debug_mode = false

# Test Configuration
test_accounts_enabled = true
test_mining_enabled = true
test_privacy_enabled = true
