[package]
name = "minimal-test"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
